networks:
  daomed_network:
    driver: bridge

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: daomed-qdrant
    ports:
      - "6333:6333"
    volumes:
      - daomed_qdrant_data:/qdrant/storage
    restart: unless-stopped
    networks:
      - daomed_network

  postgres:
    image: postgres:15
    container_name: daomed-postgres
    environment:
      POSTGRES_USER: daomed
      POSTGRES_PASSWORD: daomed_pass
      POSTGRES_DB: daomed_db
    ports:
      - "5432:5432"
    volumes:
      - daomed_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - daomed_network

  minio:
    image: quay.io/minio/minio:latest
    container_name: daomed-minio
    ports:
      - "9100:9000"
      - "9101:9001"
    environment:
      MINIO_ROOT_USER: daomed
      MINIO_ROOT_PASSWORD: daomed_secret
    command: server /data --console-address ":9001"
    volumes:
      - daomed_minio_data:/data
    restart: unless-stopped
    networks:
      - daomed_network

  backend:
    build: ./backend
    container_name: daomed-backend
    ports:
      - "5050:5050"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=daomed_db
      - POSTGRES_USER=daomed
      - POSTGRES_PASSWORD=daomed_pass
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=daomed
      - MINIO_SECRET_KEY=daomed_secret
      - MINIO_BUCKET_NAME=daomed-files
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - SECRET_KEY=daomed_secret_key
      - MODEL_PATH=/app/models/vietnamese-bi-encoder
    depends_on:
      - postgres
      - minio
      - qdrant
    volumes:
      - ./backend:/app
      - ./models:/app/models
    restart: unless-stopped
    networks:
      - daomed_network

volumes:
  daomed_qdrant_data:
  daomed_postgres_data:
  daomed_minio_data: 